pipeline {
    agent any
    tools {
        maven 'Maven'  
        jdk 'JAVA_HOME'
    }
    stages {
        stage ('Compile Stage') {
            steps {
                bat 'mvn -f demo/pom.xml clean compile'
            }
        }
        
        stage ('Testing Stage') {
            steps {
                bat'mvn -f demo/pom.xml test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
        /*stage ('Install Stage') {
            steps {
                   bat'mvn -f demo/pom.xml install'
            }
        }*/
    }
}
